### PR TITLE
Added accurate messages depending on the status of the GroupChatView

### PR DESCRIPTION
**Pull request by hemmatio**
### Pull Request Title

Added accurate messages depending on the status of the GroupChatView
---

### Description

This PR introduces dynamic and accurate status messages in the `GroupChatView` to improve user experience. Depending on the state of the group chat (e.g., no group selected, no messages sent yet, or messages loading), the displayed messages now guide users more effectively.

---

### Changes
- Updated initializeMessages to handle dynamic labels based on the group chat's state.
- Introduced a helper method getLoadingLabel to generate appropriate labels based on the current group status.
- Adjusted the refreshGroups method to use the new dynamic labels.

Files Modified:
- `src/views/GroupChatView.java`

---

### CODE REVIEW

**Review by samyasnoun — CHANGES_REQUESTED** [review]
Great work on the pull request! The implementation looks solid, and I can see the effort that has gone into making the changes.

Thanks for your work on this, and keep it up!

**Review by kevinyyyeh — CHANGES_REQUESTED** [review]
The comments are more accurate now which makes more sense. Maybe add more comments on your code so it's easier to follow. Also, make sure the size of the text is not too small. Otherwise, it's looking good.

**Comment by hemmatio** [comment]
> The comments are more accurate now which makes more sense. Maybe add more comments on your code so it's easier to follow. Also, make sure the size of the text is not too small. Otherwise, it's looking good.

I've added a docstring to the `GetLoadingLabel()` function to make it easier to follow. Additionally, as the text size follows the same size as all other messages for consistency, I believe it is not too small.

**Review by kevinyyyeh — APPROVED** [review]
Perfect, it's easier to follow now. Thank you.

**Review by samyasnoun — APPROVED** [review]

**Pull request merged**
